version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "10.0.x"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "14:00"
    target-branch: "9.4.x"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "14:00"
    target-branch: "10.0.x"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "14:00"
    target-branch: "11.0.x"
    open-pull-requests-limit: 10
